#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Crosswall.Resource", IsApplication=false)]

namespace Crosswall
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public static int btn_blur = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int btn_cornerRadius = 2130771971;
			
			// aapt resource value: 0x7f010005
			public static int btn_pressColor = 2130771973;
			
			// aapt resource value: 0x7f010001
			public static int btn_strokeColor = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int btn_strokeWidth = 2130771968;
			
			// aapt resource value: 0x7f010007
			public static int btn_text_pressColor = 2130771975;
			
			// aapt resource value: 0x7f010006
			public static int btn_text_unpressColor = 2130771974;
			
			// aapt resource value: 0x7f010004
			public static int btn_unpressColor = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020000
			public static int library_name = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f030000
			public static int Crosswall = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int Crosswall_IOSButton = 2130903041;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] IOSButton = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 2
			public static int IOSButton_btn_blur = 2;
			
			// aapt resource value: 3
			public static int IOSButton_btn_cornerRadius = 3;
			
			// aapt resource value: 5
			public static int IOSButton_btn_pressColor = 5;
			
			// aapt resource value: 1
			public static int IOSButton_btn_strokeColor = 1;
			
			// aapt resource value: 0
			public static int IOSButton_btn_strokeWidth = 0;
			
			// aapt resource value: 7
			public static int IOSButton_btn_text_pressColor = 7;
			
			// aapt resource value: 6
			public static int IOSButton_btn_text_unpressColor = 6;
			
			// aapt resource value: 4
			public static int IOSButton_btn_unpressColor = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
